### ISSUE TITLE
/Uncommon/Net/UncommonRequestOptions.cs#L10

### ISSUE THREAD

**Issue by elblondo** [Xciles/Uncommon#1]
Although HttpHeaders can be used it requires an custom implementation of the abstract class HttpHeaders class. Can you provide a HttpHeaders implementation which we could use directly, for example UncommonHttpHeaders?

**Comment by Xciles** [comment]
This has been added already in a beta push to nuget (1.3.4-beta).

Commit: 2080a2ca9272cb314cde343c1263b0db7de7914a

When creating a UncommonRequestOptions you can add any headers you like to the existing instance. Or override it with your own instance.

**Comment by Xciles** [comment]
Has also been pushed to nuget in version 1.4!
